### PR TITLE
Add puppeteer object property to use different libraries 

### PR DESCRIPTION
**Pull request by cuire**
Recently I wanted to use package along with AWS Lambda (#70).  It seems to me that this functionality will not interfere with the work of the package and will help in rare cases. #80

```js
const chrome = require('chrome-aws-lambda');
const nodeHtmlToImage = require('node-html-to-image')
const puppeteerCore = require('puppeteer-core');

const image = await nodeHtmlToImage({
  html: '<html><body><div>Hello</div></body></html>',
  puppeteer: puppeteerCore,
  puppeteerArgs: {
      args: chromium.args,
      executablePath: await chrome.executablePath,
  }
})
```

### CODE REVIEW

**Comment by frinyvonnick** [comment]
Hey @cuire 👋 

Thank you for opening this pull request, I think a lot of people are waiting for this 🙏 I see you made the changes to support node 12 but the current LTS version is 16.15.1. I see two possibilities:
- We make this pull request work with the CI set to node 12 then I update it to LTS version and upgrade dependencies
- We do it all at once in this pull request

What do you prefer?

**Comment by frinyvonnick** [comment]
I pushed a commit that set the node version in the CI. You can now use latest versions of puppeteer-core 😉

**Comment by cuire** [comment]
I updated dependencies with  `yarn upgrade --latest`, then install **@types/node 16**. And remove **@types/handlebars**
`warning @types/handlebars@4.1.0: This is a stub types definition. handlebars provides its own type definitions, so you do not need this installed.`

Also I fix TS2532 in [these lines](https://github.com/frinyvonnick/node-html-to-image/blob/db0c45f7b52a6dd31a8618d2f0dcb5f862d570aa/src/main.integration.spec.ts#L149-L150) by adding [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining)
```js
expect(result?.[0]).toBeInstanceOf(Buffer);
expect(result?.[1]).toBeInstanceOf(Buffer);
```

But build fails.
`node_modules/puppeteer/lib/types.d.ts:6329:14 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.`

Should I revert the changes, or are we setting the es target to 2015, which is what the puppeter library wants.

**Comment by frinyvonnick** [comment]
Setting the es target to 2015 looks fine to me 😄

**Comment by cuire** [comment]
> Setting the es target to 2015 looks fine to me 😄
> 
> For the two lines, I don't understand why we should add optional chaining this array should be present and have exactly 2 elements in it 🤔 Could you explain it to me?

https://typescript.tv/errors/#TS2532

Since `nodeHtmlToImage` can return undefined, the typescript warns about this in the editor. And it annoyed me a little bit.

errors

**Comment by frinyvonnick** [comment]
Oh, thank you for the explanation 🙏 I'll take care of the yarn.lock file 😄 (It's because I merged two PRs from a bot that fix vulnerabilities)

**Comment by tijevlam** [comment]
Could we get this pull request to be finalized and released? That would help me a lot! :-)

**Comment by frinyvonnick** [comment]
Hello @tijevlam 👋

I'm on vacations. I'll take care of it when returning home.

**Comment by tijevlam** [comment]
Hi @frinyvonnick!  👋

No problem, enjoy your vacation!

**Review by frinyvonnick — APPROVED** [review]
Looks good to me @cuire, thank you 🙏

**Comment by rodleviton** [comment]
Hi @frinyvonnick is it possible to get these updates released?

**Comment by frinyvonnick** [comment]
Hello @rodleviton 👋 I'll do it as soon as possible 😄

**Comment by frinyvonnick** [comment]
Released in [3.3.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.3.0) 🚀

**Pull request merged**
