### PR TITLE
Adding custom "timeout" option

### PR DESCRIPTION
**Pull request by adasq**
# The problem: 

We can't set a custom `timeout` (Passing it through `puppeteerArgs` doesn't work as expected)

# Solution

A new option has been added. The `timeout` value (default `30000` ms) is passed to:
- `puppeteer-cluster` dependency (since the package has it's own `timeout` monitoring)
- and to `puppeteer` itself (via `page.setDefaultTimeout()`)

### CODE REVIEW

**Comment by adasq** [comment]
It closes: https://github.com/frinyvonnick/node-html-to-image/issues/179

**Comment by calcey-s** [comment]
> # The problem:
> We can't set a custom `timeout` (Passing it through `puppeteerArgs` doesn't work as expected)
> 
> # Solution
> A new option has been added. The `timeout` value (default `30000` ms) is passed to:
> 
> * `puppeteer-cluster` dependency (since the package has it's own `timeout` monitoring)
> * and to `puppeteer` itself (via `page.setDefaultTimeout()`)

Any plans to release this solution soon?

**Comment by adasq** [comment]
This MR is released under: https://www.npmjs.com/package/nhti
I couldn't wait...

**Comment by frinyvonnick** [comment]
Hi 👋 I do it on my free time. As soon as possible, I'll take care of opened pull requests but I can give you an estimated time. I suggest to use the package from @adasq during the mean time. It would be cool to have some automated canary version so I could merge pull requests without being in the urge of publishing a new version which takes time 💡

**Comment by ariv803** [comment]
@adasq can you provide an example of usage please?

**Comment by adasq** [comment]
It's just another option:

```
const nodeHtmlToImage = require('nhti') // https://www.npmjs.com/package/nhti

nodeHtmlToImage({
  output: './image.png',
  timeout: 1000 * 60 * 5, // 5 min
  html: '<html><body>Hello world!</body></html>'
})
  .then(() => console.log('The image was created successfully!'))
```

**Comment by frinyvonnick** [comment]
Hi @adasq 👋 I just removed some lint comments otherwise everything looks good to me, thanks 🙏

**Comment by frinyvonnick** [comment]
It has been published in [3.4.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.4.0) 🚀

**Pull request merged**
