### PR TITLE
Add new option to register handlebars helpers

### PR DESCRIPTION
**Pull request by fcolacilli**
Added a new option to register handlebars helpers before template compilation

### CODE REVIEW

**Comment by frinyvonnick** [comment]
Hi @fcolacilli 👋 

Thank you for opening this pull request 🙏 

Can you provide an example of usage, please? Also, I would appreciate if you could add documentation and tests for this new option.

**Comment by fcolacilli** [comment]
This is used to add custom logic to the templates. The idea is taken from the [handlebars docs](https://handlebarsjs.com/guide/builtin-helpers.html#sub-expressions).

For example, if I had a variable and wanted to do some conditional rendering depending on its value, I could define a helper function and then put the logic in the template like this:

```
nodeHtmlToImage({
  output: './image.png',
  content: { myVar: 'foo' },
  handlebarsHelpers: {
    equals: (a, b) => a === b,
  },
  html: `
    <html>
      <body>
        {{#if (equals myVar 'foo')}}<div>Foo</div>{{/if}}
        {{#if (equals myVar 'bar')}}<div>Bar</div>{{/if}}
      </body>
    </html>`
  
})
```

Of course, this is an easy example, but it opens the way to more complex logic.

I'll be adding the docs and tests in the next days.

**Comment by frinyvonnick** [comment]
Gentle ping @fcolacilli 👋 

Do you think you will have time to finish this pull request?

**Comment by fcolacilli** [comment]
Yes, sorry for the delay 😟. I've been really busy during the last month.
I'll try to make some time next week to finish this.

**Comment by frinyvonnick** [comment]
Hi @fcolacilli 👋 

Sorry for the delay 😅 I rebased your branch on master and migrated to Typescript. The tests are all green but could you do so functionnal test to ensure everything is fine following my work?

**Comment by BobTheShoplifter** [comment]
Is this deployed? Did not find anything in the docs but would be awsome!

**Comment by fcolacilli** [comment]
Hi! Sorry for the delay. Are these tests ok?

**Review by frinyvonnick — APPROVED** [review]

**Comment by frinyvonnick** [comment]
Looks good to me, thank you @fcolacilli :pray:

**Comment by frinyvonnick** [comment]
Released in [3.3.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.3.0) 🚀

**Pull request merged**
