### PR TITLE
✨ rewrite to TypeScript

### PR DESCRIPTION
**Pull request by Favna**
I went ahead and rewrote the entire lib to TypeScript to ensure perfect type safety. My primary reason was that I want to use this in TypeScript project and so I needed types but once I started writing them I figured I might as well just rewrite the lib since it's not that much code when it comes down to it.

All in all this is what is changed
- `src` files are now in TS
- test files are moved to `tests` directory, gives a cleaner split between them and produces a cleaner bundle when compiled by TypeScript.
- test files are also in TypeScript, leveraging `ts-jest` to fully compile TS before running tests
- scripts in package.json have been expanded to include build, watch and clean for TypeScript
- jest config has been updated to reflect earlier mentioned changes
- bumped handlebars, puppeteer and tesseract.js within version spec
- Specified where TypeScript should find the types in package.json
- Specified a "files" array in package.json to ensure only those files that need publishing to NPM are actually included in the tarball. Previous publishes had junk files: 
image
- Added the options for the function as a TypeScript interface, using the data from the README to add all the descriptions / defaults / etc.
- Made sure tests output the images to the current directory, I was facing some issues with this on Windows where it wouldn't read the proper directory.
- Allowed Jest to retry failed tests twice (a feature of the new jest-circus runner) just in case tessarect fails (it occasionally did for me)
- Allowed Jest a longer timeout for the same reason as above.

### CODE REVIEW

**Comment by frinyvonnick** [comment]
Hi @Favna, Thank you for opening this pull request.

Adding support for Typescript users is a great idea. I'm not familiar with Typescript and it adds a build step so I would prefer to expose types rather than rewriting the library. 

Are you interested in writing the `index.d.ts`?

**Comment by Favna** [comment]
I suppose I could do that, yes. 

Should I also keep the changes I made to the test structure? I mean, the retry attempts and allowing a longer timeout, not so much the location of the files.

I do also want to keep the "files" array in package.json if that's alright with you. I think this is a fantastic library (using it to great success already) but NPM downloading useless files is a huge turn down for me.

**Comment by frinyvonnick** [comment]
Sure, these are great ideas. But I would prefer having separate pull requests (Typescript support, enchance tests and cleaning published files) 👍 

Thank you for all these suggestions 👏

**Comment by Favna** [comment]
#43, #44 and #45 are created @frinyvonnick. So I'll close this PR.

**Pull request closed without merging**
