### PR TITLE
Render specified element

### PR DESCRIPTION
**Pull request by SilveryStar**
Add feature: use the element option to specify the element to generate an image (can be used with content)

### CODE REVIEW

**Comment by SilveryStar** [comment]
@frinyvonnick There was an error in my pull requests during `Run yarn test`.
```
FAIL src/index.spec.js (23.261 s)
  ● node-html-to-image › batch › should create two images
    ENOENT: no such file or directory, open './generated/image1.png'
  ● node-html-to-image › batch › should return two buffe
```
I think the reason lies in the test data, because the new option `element` cannot be empty in `content` (like output)

**Comment by frinyvonnick** [comment]
Hi @SilveryStar 👋 

Thank you for opening this pull request 🙏  Sorry for the late response I was in holidays then started a new job so I didn't have a lot of time. I'll give it a look as soon as possible 👍

**Comment by frinyvonnick** [comment]
@SilveryStar a pull request that passes tests has been opened #87 but It lacks documentation and the one you did here looks really great. Maybe you can merge both work?

**Comment by frinyvonnick** [comment]
Done in #114

**Comment by frinyvonnick** [comment]
This was released in [v3.2.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v3.2.0) 🚀

**Pull request closed without merging**
