### PR TITLE
allow overriding the page viewport

### PR DESCRIPTION
**Pull request by aequasi**
Allows users to change the viewport size, and the deviceScaleFactor (which allows us to create higher resolution images)

### CODE REVIEW

**Comment by frinyvonnick** [comment]
Hello @aequasi 👋 

Thank you for opening this pull request 🙏 . Could you add documentation about this property in the README and a test to ensure it works fine (and avoid regression in the future), please?

**Comment by frinyvonnick** [comment]
Gentle ping @aequasi 👋 

I won't be able to merge it without documentation and a test 😢

**Comment by aequasi** [comment]
No worries. I, unfortunately, can't find the time to add tests and documentation. I'll close this out.

**Comment by frinyvonnick** [comment]
No problem, if you find some time in the future and want to add this property feel free to reopen this pull request 👍

**Pull request closed without merging**
