### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by jewkesy**
Allow encoding type to be passed in.

Revised `output` check if using encoding value

### CODE REVIEW

**Comment by frinyvonnick** [comment]
Hi @jewkesy, 

Thank your for considering contributing to `node-html-to-image` 👍 . The way you checked encoding at line 16 make this parameter mandatory. It should be optional since it works fine most of the time without passing it. Could you make it optional, please?

**Comment by jewkesy** [comment]
Hi @frinyvonnick, thank you for the reply.  

What are your intentions with the use of `output` when only requiring the buffer output?  Providing an empty value will ensure Puppeteer will not save the image to disk. 

Would you prefer a check that ensures the value does not equal `base64` when providing`output`?  I can see no reason why a user would chose to save the `base64` content to disk.

**Comment by frinyvonnick** [comment]
I want to make usage of these two properties optional, since you can provide encoding without output to get a buffer or provide an output without encoding if you want the default binary. You can even provide none of them if you want to return the binary as a buffer in a request for example.

Resolving issue #12 will remove the error produce if you don't provide an output. I suggest to revert your change at line `16`.

Could you add the encoding property in the table of properties in the README.md? It will be good to me then 👌

**Comment by jewkesy** [comment]
Hi @frinyvonnick 
I've reverted the line change and updated the README with the encoding option.

**Comment by frinyvonnick** [comment]
Nice, thank you @jewkesy 👍

**Comment by frinyvonnick** [comment]
It has been published in [2.0.0](https://github.com/frinyvonnick/node-html-to-image/releases/tag/v2.0.0) 🚀

**Pull request merged**
